### ISSUE TITLE
No compability with motd

### ISSUE THREAD

**Issue by XRominjol** [Syrent/VelocityVanish#161]
### Server backend version

Spigot

### Server Velocity version

Velocity latest

### VelocityVanish version

3.18.2

### Describe the bug

Idk how to hide vanished players in motd, i found Compatibility page in git and i found minimotd compability (idk what is it, im tried to find some options of how to use it and i didnt found something) and i found a ServerListPlus compability, but i have a question. How i need to use ServerListPlus if it bungeecord only ?? Latest update of Server list plus was in 2017.

### Expected behavior

nothing

### Steps to reproduce

nothing

### Checklist

- [X] I am running latest version of the plugin on both Velocity and Spigot
- [X] I have read the wiki to make sure it's not an issue with configuration
- [ ] I ticked all of the boxes without actually reading them

**Comment by Syrent** [comment]
You need to use ServerListPlus development builds (https://ci.codemc.org/job/Minecrell/job/ServerListPlus/) with VelocityVanish custom placeholders (https://github.com/Syrent/VelocityVanish/wiki/Placeholders).
Also, I recommend you use MiniMOTD instead of ServerListPlus (https://modrinth.com/plugin/minimotd)
