### ISSUE TITLE
[suggestion/help] fix chatmanger velocity incompatability

### ISSUE THREAD

**Issue by modpotato** [Syrent/VelocityVanish#326]
though im unsure why, when you have [chatmanager](https://modrinth.com/plugin/chatmanager) installed on a server and using a velocity version of sayanvanish it doesnt work properly. the reason im confused is theoretically (looking at the src for this against chatmanager) it should work? for example

https://github.com/Crazy-Crew/ChatManager/blob/61f8ad3bea7b9ba1a644553fff8005565a938342/src/main/java/com/ryderbelserion/chatmanager/plugins/VanishSupport.java#L24-L40
this is in the latest update though in the past they had the following:
https://github.com/Crazy-Crew/ChatManager/blob/badd9060b2adf42a2d2b44f378360a86585f082e/src/main/java/me/h1dd3nxn1nja/chatmanager/support/vanish/GenericVanishSupport.java#L9-L16
which is effectively the exact same

and in sayanvanish you set the vanished bool for the player to true as well? so as a result i just dont understand why its not compatible. i was running sayanvanish on velocity with a backend on paper 1.20.6 (latest build of the time) and would get join messages whenever i was vanished though it didnt happen with supervanish or premiumvanish.

**Comment by Syrent** [comment]
The "vanished" meta is indeed `true`, but the join message is still being sent. Based on my review of the ChatManager source code, the `isVanished` method is primarily used for tasks like tab completions ([here](https://github.com/Crazy-Crew/ChatManager/blob/61f8ad3bea7b9ba1a644553fff8005565a938342/src/main/java/me/h1dd3nxn1nja/chatmanager/commands/tabcompleter/TabCompleteMessage.java#L49) and [here](https://github.com/Crazy-Crew/ChatManager/blob/61f8ad3bea7b9ba1a644553fff8005565a938342/src/main/java/me/h1dd3nxn1nja/chatmanager/commands/CommandMessage.java#L162)). I did not find any vanish checks in the [join/quit listeners](https://github.com/Crazy-Crew/ChatManager/blob/61f8ad3bea7b9ba1a644553fff8005565a938342/src/main/java/me/h1dd3nxn1nja/chatmanager/listeners/ListenerPlayerJoin.java).

It seems that SuperVanish and PremiumVanish handle the removal of join/quit messages independently, rather than ChatManager disabling these messages for vanished users. While I can implement this myself, I believe it would be better if the ChatManager developer added a check for vanished players on join/quit and handled the message accordingly.

(I'm still not completely certain if ChatManager has a check for vanished users on join and quit, but I couldn't find anything indicating that it does.)
